[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'php82Extensions.pdo_pgsql', 'php82Extensions.gd', 'php82Extensions.zip', 'php82Extensions.intl', 'php82Extensions.xmlrpc', 'php82Extensions.soap', 'php82Extensions.mbstring', 'php82Extensions.curl']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader || true']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'