[phases.setup]
nixPkgs = [
  'php82', 
  'php82Extensions.mysqli',
  'php82Extensions.pgsql',
  'php82Extensions.pdo',
  'php82Extensions.pdo_pgsql', 
  'php82Extensions.gd', 
  'php82Extensions.zip', 
  'php82Extensions.intl',
  'php82Extensions.xmlrpc', 
  'php82Extensions.soap', 
  'php82Extensions.mbstring', 
  'php82Extensions.curl',
  'php82Extensions.opcache',
  'php82Extensions.dom',
  'php82Extensions.xml'
]

[phases.install]
cmds = [
  'mkdir -p moodledata',
  'chmod 777 moodledata'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'